standalone_tags:
  [
{id: 0, size: 0.096},
{id: 1, size: 0.096},
{id: 2, size: 0.096},
{id: 3, size: 0.096},
{id: 4, size: 0.096},
{id: 5, size: 0.096},
{id: 6, size: 0.096},
{id: 7, size: 0.096},
{id: 8, size: 0.096},
{id: 9, size: 0.096},
{id: 10, size: 0.096},
{id: 11, size: 0.096},
{id: 12, size: 0.096},
{id: 13, size: 0.096},
{id: 14, size: 0.096},
{id: 15, size: 0.096},
{id: 16, size: 0.096},
{id: 17, size: 0.096},
{id: 18, size: 0.096},
{id: 19, size: 0.096},
{id: 20, size: 0.096},
{id: 21, size: 0.096},
{id: 22, size: 0.096},
{id: 23, size: 0.096},
{id: 24, size: 0.096},
{id: 25, size: 0.096},
{id: 26, size: 0.096},
{id: 27, size: 0.096},
{id: 28, size: 0.096},
{id: 29, size: 0.096},
{id: 30, size: 0.096},
{id: 31, size: 0.096},
{id: 32, size: 0.096},
{id: 33, size: 0.096},
{id: 34, size: 0.096},
{id: 35, size: 0.096},
{id: 36, size: 0.096},
{id: 37, size: 0.096},
{id: 38, size: 0.096},
{id: 39, size: 0.096},
{id: 40, size: 0.096},
{id: 41, size: 0.096},
{id: 42, size: 0.096},
{id: 43, size: 0.096},
{id: 44, size: 0.096},
{id: 45, size: 0.096},
{id: 46, size: 0.096},
{id: 47, size: 0.096},
{id: 48, size: 0.096},
{id: 49, size: 0.096},
{id: 50, size: 0.096},
{id: 51, size: 0.096},
{id: 52, size: 0.096},
{id: 53, size: 0.096},
{id: 54, size: 0.096},
{id: 55, size: 0.096},
{id: 56, size: 0.096},
{id: 57, size: 0.096},
{id: 58, size: 0.096},
{id: 59, size: 0.096},
{id: 60, size: 0.096},
{id: 61, size: 0.096},
{id: 62, size: 0.096},
  ]
